; Inventaire des VM du projet POC CI/CD
; Adapte ansible_user si besoin (le nom d'utilisateur SSH sur chaque VM)

[vm1_jenkins]
192.168.86.134 ansible_user=jules

[vm2_sonarqube]
192.168.86.135 ansible_user=jules

; Groupe pratique pour cibler les deux VM d'un coup (ex: installation Docker)
[docker_hosts:children]
vm1_jenkins
vm2_sonarqube
